export const weatherStatistics = [
    {
        id: 1,
        location: {
            name: 'New York',
            region: 'New York, New York',
            country: 'USA',
            lat: 51.52,
            lon: -0.11,
            tz_id: 'Europe/London',
            localtime_epoch: 1660323435,
            localtime: '2022-13-08 3:05',
        },
        current: {
            temp_c: 17.6,
            max_temp_c: 17.6,
            min_temp_c: 17.6,
            precip_mm: 24.5,
            chance_of_rain: 78,
        },
        forecast: {
            forecastday: [
                {
                    time_epoch: 1660323435,
                    time: '2022-08-12',
                    max_temp_c: 17.6,
                    min_temp_c: 7.6,
                    precip_mm: 24.5,
                    chance_of_rain: 78,
                    eta: 5,
                },
                {
                    time_epoch: 1660409835,
                    time: '2022-08-13',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 7,
                    chance_of_rain: 69,
                    eta: 10,
                },
                {
                    time_epoch: 1660496235,
                    time: '2022-08-14',
                    max_temp_c: 22.6,
                    min_temp_c: undefined,
                    precip_mm: 0.5,
                    will_it_rain: 1,
                    chance_of_rain: 12,
                },
                {
                    time_epoch: 1660582635,
                    time: '2022-08-15',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
                {
                    time_epoch: 1660669035,
                    time: '2022-08-16',
                    max_temp_c: 32.6,
                    min_temp_c: 20,
                    precip_mm: 0,
                    chance_of_rain: 0,
                },
                {
                    time_epoch: 1660755435,
                    time: '2022-08-17',
                    max_temp_c: 35.6,
                    min_temp_c: 21.6,
                    precip_mm: 20,
                    chance_of_rain: 3,
                },
                {
                    time_epoch: 1660841835,
                    time: '2022-08-18',
                    max_temp_c: undefined,
                    min_temp_c: undefined,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
            ],
        },
        alert: {},
    },
    {
        id: 2,
        location: {
            name: 'Miami',
            region: 'California, Miami',
            country: 'USA',
            lat: 51.52,
            lon: -0.11,
            tz_id: 'Europe/London',
            localtime_epoch: 1660323435,
            localtime: '2022-13-08 3:05',
            eta: undefined,
        },
        current: {
            temp_c: 17.6,
            max_temp_c: 17.6,
            min_temp_c: 17.6,
            precip_mm: 24.5,
            chance_of_rain: 78,
        },
        forecast: {
            forecastday: [
                {
                    time_epoch: 1660323435,
                    time: '2022-08-12',
                    max_temp_c: 17.6,
                    min_temp_c: 7.6,
                    precip_mm: 24.5,
                    chance_of_rain: 78,
                    eta: 5,
                },
                {
                    time_epoch: 1660409835,
                    time: '2022-08-13',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 7,
                    chance_of_rain: 69,
                },
                {
                    time_epoch: 1660496235,
                    time: '2022-08-14',
                    max_temp_c: 22.6,
                    min_temp_c: undefined,
                    precip_mm: 0.5,
                    will_it_rain: 1,
                    chance_of_rain: 12,
                },
                {
                    time_epoch: 1660582635,
                    time: '2022-08-15',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 20,
                    chance_of_rain: 26,
                    eta: 30,
                },
                {
                    time_epoch: 1660669035,
                    time: '2022-08-16',
                    max_temp_c: 32.6,
                    min_temp_c: 20,
                    precip_mm: 0,
                    chance_of_rain: 0,
                },
                {
                    time_epoch: 1660755435,
                    time: '2022-08-17',
                    max_temp_c: 35.6,
                    min_temp_c: 21.6,
                    precip_mm: 20,
                    chance_of_rain: 3,
                },
                {
                    time_epoch: 1660841835,
                    time: '2022-08-18',
                    max_temp_c: undefined,
                    min_temp_c: undefined,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
            ],
        },
        alert: {},
    },
    {
        id: 3,
        location: {
            name: 'Tel-Aviv',
            region: 'Tel-Aviv, Israel',
            country: 'Israel',
            lat: 51.52,
            lon: -0.11,
            tz_id: 'Europe/London',
            localtime_epoch: 1660323435,
            localtime: '2022-13-08 3:05',
            eta: 10,
        },
        current: {
            temp_c: 19.2,
            max_temp_c: 120.6,
            min_temp_c: 17.6,
            precip_mm: 24.5,
            chance_of_rain: 78,
        },
        forecast: {
            forecastday: [
                {
                    time_epoch: 1660323435,
                    time: '2022-08-12',
                    max_temp_c: 32.6,
                    min_temp_c: 7.6,
                    precip_mm: 24.5,
                    chance_of_rain: 78,
                },
                {
                    time_epoch: 1660409835,
                    time: '2022-08-13',
                    max_temp_c: 24.6,
                    min_temp_c: 6.6,
                    precip_mm: 7,
                    chance_of_rain: 69,
                },
                {
                    time_epoch: 1660496235,
                    time: '2022-08-14',
                    max_temp_c: 22.6,
                    min_temp_c: undefined,
                    precip_mm: 0.5,
                    will_it_rain: 1,
                    chance_of_rain: 12,
                },
                {
                    time_epoch: 1660582635,
                    time: '2022-08-15',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
                {
                    time_epoch: 1660669035,
                    time: '2022-08-16',
                    max_temp_c: 32.6,
                    min_temp_c: 20,
                    precip_mm: 0,
                    chance_of_rain: 0,
                    eta: 70,
                },
                {
                    time_epoch: 1660755435,
                    time: '2022-08-17',
                    max_temp_c: 35.6,
                    min_temp_c: 21.6,
                    precip_mm: 20,
                    chance_of_rain: 3,
                },
                {
                    time_epoch: 1660841835,
                    time: '2022-08-18',
                    max_temp_c: undefined,
                    min_temp_c: undefined,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
            ],
        },
        alert: {},
    },
    {
        id: 4,
        location: {
            name: 'Cluj Napoca',
            region: 'Cluj Napoca, Cluj',
            country: 'Roamnia',
            lat: 51.52,
            lon: -0.11,
            tz_id: 'Europe/London',
            localtime_epoch: 1660323435,
            localtime: '2022-13-08 3:05',
            eta: 120,
        },
        current: {
            temp_c: 34,
            max_temp_c: 17.6,
            min_temp_c: 17.6,
            precip_mm: 24.5,
            chance_of_rain: 78,
        },
        forecast: {
            forecastday: [
                {
                    time_epoch: 1660323435,
                    time: '2022-08-12',
                    max_temp_c: 17.6,
                    min_temp_c: 7.6,
                    precip_mm: 24.5,
                    chance_of_rain: 78,
                    eta: 78,
                },
                {
                    time_epoch: 1660409835,
                    time: '2022-08-13',
                    max_temp_c: 40,
                    min_temp_c: 6.6,
                    precip_mm: 7,
                    chance_of_rain: 69,
                    eta: 2,
                },
                {
                    time_epoch: 1660496235,
                    time: '2022-08-14',
                    max_temp_c: 37.2,
                    min_temp_c: undefined,
                    precip_mm: 0.5,
                    will_it_rain: 1,
                    chance_of_rain: 12,
                },
                {
                    time_epoch: 1660582635,
                    time: '2022-08-15',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
                {
                    time_epoch: 1660669035,
                    time: '2022-08-16',
                    max_temp_c: 32.6,
                    min_temp_c: 20,
                    precip_mm: 0,
                    chance_of_rain: 0,
                },
                {
                    time_epoch: 1660755435,
                    time: '2022-08-17',
                    max_temp_c: 35.6,
                    min_temp_c: 21.6,
                    precip_mm: 20,
                    chance_of_rain: 3,
                },
                {
                    time_epoch: 1660841835,
                    time: '2022-08-18',
                    max_temp_c: undefined,
                    min_temp_c: undefined,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
            ],
        },
        alert: {},
    },
    {
        id: 5,
        location: {
            name: 'Bucharest',
            region: 'Bucharest, Ilfov',
            country: 'Romania',
            lat: 51.52,
            lon: -0.11,
            tz_id: 'Europe/London',
            localtime_epoch: 1660323435,
            localtime: '2022-13-08 3:05',
        },
        current: {
            temp_c: 20,
            max_temp_c: 17.6,
            min_temp_c: 17.6,
            precip_mm: 24.5,
            chance_of_rain: 78,
        },
        forecast: {
            forecastday: [
                {
                    time_epoch: 1660323435,
                    time: '2022-08-12',
                    max_temp_c: 17.6,
                    min_temp_c: 7.6,
                    precip_mm: 24.5,
                    chance_of_rain: 78,
                    eta: 109,
                },
                {
                    time_epoch: 1660409835,
                    time: '2022-08-13',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 7,
                    chance_of_rain: 69,
                    eta: 78,
                },
                {
                    time_epoch: 1660496235,
                    time: '2022-08-14',
                    max_temp_c: 22.6,
                    min_temp_c: undefined,
                    precip_mm: 0.5,
                    will_it_rain: 1,
                    chance_of_rain: 12,
                },
                {
                    time_epoch: 1660582635,
                    time: '2022-08-15',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
                {
                    time_epoch: 1660669035,
                    time: '2022-08-16',
                    max_temp_c: 32.6,
                    min_temp_c: 20,
                    precip_mm: 0,
                    chance_of_rain: 0,
                },
                {
                    time_epoch: 1660755435,
                    time: '2022-08-17',
                    max_temp_c: 35.6,
                    min_temp_c: 21.6,
                    precip_mm: 20,
                    chance_of_rain: 3,
                },
                {
                    time_epoch: 1660841835,
                    time: '2022-08-18',
                    max_temp_c: undefined,
                    min_temp_c: undefined,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
            ],
        },
        alert: {},
    },
    {
        id: 6,
        location: {
            name: 'Brussels',
            region: 'Brussels, Belgium',
            country: 'Belgium',
            localtime_epoch: 1660323435,
            localtime: '2022-13-08 3:05',
        },
        current: {
            temp_c: 17.6,
            max_temp_c: 17.6,
            min_temp_c: 17.6,
            precip_mm: 24.5,
            chance_of_rain: 78,
        },
        forecast: {
            forecastday: [
                {
                    time_epoch: 1660323435,
                    time: '2022-08-12',
                    max_temp_c: 17.6,
                    min_temp_c: 7.6,
                    precip_mm: 24.5,
                    chance_of_rain: 78,
                },
                {
                    time_epoch: 1660409835,
                    time: '2022-08-13',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 7,
                    chance_of_rain: 69,
                },
                {
                    time_epoch: 1660496235,
                    time: '2022-08-14',
                    max_temp_c: 22.6,
                    min_temp_c: undefined,
                    precip_mm: 0.5,
                    will_it_rain: 1,
                    chance_of_rain: 12,
                },
                {
                    time_epoch: 1660582635,
                    time: '2022-08-15',
                    max_temp_c: 19.6,
                    min_temp_c: 6.6,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
                {
                    time_epoch: 1660669035,
                    time: '2022-08-16',
                    max_temp_c: 32.6,
                    min_temp_c: 20,
                    precip_mm: 0,
                    chance_of_rain: 0,
                },
                {
                    time_epoch: 1660755435,
                    time: '2022-08-17',
                    max_temp_c: 35.6,
                    min_temp_c: 21.6,
                    precip_mm: 20,
                    chance_of_rain: 3,
                },
                {
                    time_epoch: 1660841835,
                    time: '2022-08-18',
                    max_temp_c: undefined,
                    min_temp_c: undefined,
                    precip_mm: 20,
                    chance_of_rain: 26,
                },
            ],
        },
        alert: {},
    },
];
